### ISSUE TITLE
Implementing using C#

### ISSUE THREAD

**Issue by NitroXenon** [Spl3en/LoLClientAPI#2]
So, @Spl3en you know that I'm currently developing a IRC Client using the Chat API.

Btw I found that not many users' computer has installed Python. Therefore I decided to develop the IRC client using C#. 

I can use DllImport to load the APIs' functions, but do I need to do other setup such as injecting the dlls into LoL? Or do I need to initial/execute a specific function before I use the Chat APIs? 

Thanks! ;-)

**Comment by Spl3en** [comment]
There is no specific order actually, you only need 2 things for making it work : 
- Inject LoLServerAPI.dll in the League of Legends.exe process
- LoadLibrary the LoLClientAPI.dll

When you LoadLibrary the LoLClientAPI.dll, it will connect asynchronously to the LoLServerAPI when it is ready.
All the functions exported of LoLClientAPI.dll make sure the client is connected to the server before doing anything, and will block the execution until the LoLServerAPI is ready.

So you can inject first and LoadLibrary after, or LoadLibrary and inject after, it shouldn't matter.

I suggest you taking a look at the following architecture schema if you want to better understand the architecture :

![LoLClientAPI Overview](http://i.cubeupload.com/V9fuUE.png)

**Comment by NitroXenon** [comment]
Okay got it. Thx for your reply :)
