### ISSUE TITLE
Skin Hack

### ISSUE THREAD

**Issue by NitroXenon** [Spl3en/LoLClientAPI#4]
hey it's me again.
Do you know how to make a skin hack tool? Without editing skin image files.
In my region there is a OP C++ engineer named PlusIsLand. He has been working on LoL skin hack since S3. He made a C++ dll named dinput8.dll. 

Usage : Put that dinput8.dll under the folder which League of Legends.exe located. Than after game start, dinput8.ini is generated and you can edit the skin id inside that ini file.

So I am so curious that how can I make a skin hack tool by myself? How can I find those offsets?? Thx a lot.

SkinHack dinput8.dll download : https://docs.google.com/uc?export=download&confirm=no_antivirus&id=0B17PIrvG_sqUSFAxN2tjVUp4SDA

Best regard
Peter

**Comment by Spl3en** [comment]
Hey Peter,

Sorry, I don't know much about Skin hacking, i never tried to do anything with it.

All I can say with the DLL you provided is that he uses those pattern matching for detecting the needed offsets :

"Screen Hero Image Hack Target Address"
    x??x??xx??xxx?
    \xFF\x00\x00\x8B\x00\x00\x52\xFF\x00\x00\x8B\x01\xFF\x00

"netUID Target Address"
    xxx????xxxxxxx
    \x50\x56\x68\x00\x00\x00\x00\x6A\x00\x6A\x01\x6A\x03\xE8

I don't know much more about this, sorry

**Comment by NitroXenon** [comment]
ok nvm.
